package com.example.download;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "THREAD_INFO".
*/
public class ThreadInfoDao extends AbstractDao<ThreadInfo, Long> {

    public static final String TABLENAME = "THREAD_INFO";

    /**
     * Properties of entity ThreadInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Url = new Property(1, String.class, "url", false, "URL");
        public final static Property FileName = new Property(2, String.class, "fileName", false, "FILE_NAME");
        public final static Property Start = new Property(3, long.class, "start", false, "START");
        public final static Property End = new Property(4, long.class, "end", false, "END");
        public final static Property Finished = new Property(5, long.class, "finished", false, "FINISHED");
        public final static Property FileLength = new Property(6, long.class, "fileLength", false, "FILE_LENGTH");
    }


    public ThreadInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ThreadInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"THREAD_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"URL\" TEXT NOT NULL ," + // 1: url
                "\"FILE_NAME\" TEXT NOT NULL ," + // 2: fileName
                "\"START\" INTEGER NOT NULL ," + // 3: start
                "\"END\" INTEGER NOT NULL ," + // 4: end
                "\"FINISHED\" INTEGER NOT NULL ," + // 5: finished
                "\"FILE_LENGTH\" INTEGER NOT NULL );"); // 6: fileLength
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"THREAD_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ThreadInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUrl());
        stmt.bindString(3, entity.getFileName());
        stmt.bindLong(4, entity.getStart());
        stmt.bindLong(5, entity.getEnd());
        stmt.bindLong(6, entity.getFinished());
        stmt.bindLong(7, entity.getFileLength());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ThreadInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUrl());
        stmt.bindString(3, entity.getFileName());
        stmt.bindLong(4, entity.getStart());
        stmt.bindLong(5, entity.getEnd());
        stmt.bindLong(6, entity.getFinished());
        stmt.bindLong(7, entity.getFileLength());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ThreadInfo readEntity(Cursor cursor, int offset) {
        ThreadInfo entity = new ThreadInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // url
            cursor.getString(offset + 2), // fileName
            cursor.getLong(offset + 3), // start
            cursor.getLong(offset + 4), // end
            cursor.getLong(offset + 5), // finished
            cursor.getLong(offset + 6) // fileLength
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ThreadInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUrl(cursor.getString(offset + 1));
        entity.setFileName(cursor.getString(offset + 2));
        entity.setStart(cursor.getLong(offset + 3));
        entity.setEnd(cursor.getLong(offset + 4));
        entity.setFinished(cursor.getLong(offset + 5));
        entity.setFileLength(cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ThreadInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ThreadInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ThreadInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
